project:
  type: website
  output-dir: docs
  preview:
    port: 3333

website:
  title: "CitiBike Optimization"
  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."

  sidebar:
    pinned: true
    align: center
    style: "docked"
    search: true
    collapse-level: 2
    contents:
      - href: index.qmd
        text: Welcome
      - section: Project/index.qmd
        contents:
          - Project/Project Overview.qmd
          - Project/project.ipynb

format:
  html:
    highlight-style: solarized
    theme: cosmo
    css: styles.css
    code-copy: true
    code-overflow: wrap
    toc: true
